name: bizy-ai
region: nyc

# Services
services:
  # Frontend - Static Site
  - name: frontend
    github:
      repo: reidchatham/business-agent
      branch: main
      deploy_on_push: false  # Controlled by GitHub Actions CI/CD
    source_dir: frontend
    build_command: npm run build
    output_dir: dist
    envs:
      - key: VITE_API_BASE_URL
        value: ${backend.PUBLIC_URL}/api
    routes:
      - path: /
    http_port: 80

  # Backend API - FastAPI
  - name: backend
    github:
      repo: reidchatham/business-agent
      branch: main
      deploy_on_push: false  # Controlled by GitHub Actions CI/CD
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    envs:
      # Database
      - key: DATABASE_URL
        value: ${bizy-postgres.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Redis
      - key: REDIS_URL
        value: ${bizy-redis.REDIS_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # JWT Secret (must match auth-server)
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # AI API Key
      - key: ANTHROPIC_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Application settings
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: ALLOWED_ORIGINS
        value: ${frontend.PUBLIC_URL},https://bizy.ai

      # Auth server URL (internal)
      - key: AUTH_SERVER_URL
        value: ${auth-server.PRIVATE_URL}

      # Email (SendGrid)
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: apikey
      - key: SMTP_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FROM_EMAIL
        value: noreply@bizy.ai

    http_port: 8000
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    instance_count: 1
    instance_size_slug: basic-xs

    routes:
      - path: /api

  # Auth Server - Ruby/Sinatra
  - name: auth-server
    github:
      repo: reidchatham/auth-server-ruby
      branch: main
      deploy_on_push: false  # Controlled by GitHub Actions CI/CD
    dockerfile_path: Dockerfile
    envs:
      # Environment
      - key: RACK_ENV
        value: production

      # JWT Secret (must match backend)
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      # Database (SQLite in container)
      - key: DATABASE_URL
        value: sqlite3:/app/db/production.sqlite3

      # CORS
      - key: CORS_ALLOWED_ORIGINS
        value: ${frontend.PUBLIC_URL},${backend.PUBLIC_URL}

      # Email (SendGrid)
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: apikey
      - key: SMTP_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FROM_EMAIL
        value: noreply@bizy.ai

    http_port: 4567
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    instance_count: 1
    instance_size_slug: basic-xs

    routes:
      - path: /auth

# Databases
databases:
  # PostgreSQL for backend
  - name: bizy-postgres
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    production: true

  # Redis for caching
  - name: bizy-redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb
    production: true

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
